In [5]:
!pip install kagglehub

In [7]:
import kagglehub

path = kagglehub.dataset_download("jainilcoder/netflix-stock-price-prediction")
print(path)


import os

path = r"C:\Users\HP\.cache\kagglehub\datasets\jainilcoder\netflix-stock-price-prediction\versions\1"

print(os.listdir(path))

C:\Users\HP\.cache\kagglehub\datasets\jainilcoder\netflix-stock-price-prediction\versions\1
['NFLX.csv']


In [8]:
import pandas as pd

file_path = r"C:\Users\HP\.cache\kagglehub\datasets\jainilcoder\netflix-stock-price-prediction\versions\1\NFLX.csv"

df = pd.read_csv(file_path)

print(df.head())

         Date        Open        High         Low       Close   Adj Close  \
0  2018-02-05  262.000000  267.899994  250.029999  254.259995  254.259995   
1  2018-02-06  247.699997  266.700012  245.000000  265.720001  265.720001   
2  2018-02-07  266.579987  272.450012  264.329987  264.559998  264.559998   
3  2018-02-08  267.079987  267.619995  250.000000  250.100006  250.100006   
4  2018-02-09  253.850006  255.800003  236.110001  249.470001  249.470001   

     Volume  
0  11896100  
1  12595800  
2   8981500  
3   9306700  
4  16906900  


In [9]:
import numpy as np

# Close price column ko NumPy array mein convert
prices = df['Close'].values

# Mean
print("Mean:", np.mean(prices))

# Std
print("Std:", np.std(prices))

# Daily change
change = np.diff(prices)
print("Change:", change[:5])

Mean: 419.0007329207136
Std: 108.2363234268936
Change: [ 11.460006  -1.160003 -14.459992  -0.630005   8.480011]


In [10]:
#array
arr1 = np.array(prices[:5])
arr2 = arr1.reshape(5,1)
arr3 = arr2.reshape(5,1,1)

print("\n1D Array:", arr1)
print("\n2D Array:\n", arr2)
print("\n3D Array:\n", arr3)


1D Array: [254.259995 265.720001 264.559998 250.100006 249.470001]

2D Array:
 [[254.259995]
 [265.720001]
 [264.559998]
 [250.100006]
 [249.470001]]

3D Array:
 [[[254.259995]]

 [[265.720001]]

 [[264.559998]]

 [[250.100006]]

 [[249.470001]]]


In [11]:
#Indexing & Slicing
print("\nFirst element:", arr1[0])
print("Last 3 elements:", arr1[-3:])
print("All rows second column (2D):", arr2[:,0])


First element: 254.259995
Last 3 elements: [264.559998 250.100006 249.470001]
All rows second column (2D): [254.259995 265.720001 264.559998 250.100006 249.470001]


In [12]:
#reshaping
reshaped = prices[:10].reshape(5,2)
print("\nReshaped (5x2):\n", reshaped)



Reshaped (5x2):
 [[254.259995 265.720001]
 [264.559998 250.100006]
 [249.470001 257.950012]
 [258.269989 266.      ]
 [280.269989 278.519989]]


In [13]:
#Mathematical Operations
print("\nAdd 10:", arr1 + 10)
print("Multiply by 2:", arr1 * 2)



Add 10: [264.259995 275.720001 274.559998 260.100006 259.470001]
Multiply by 2: [508.51999  531.440002 529.119996 500.200012 498.940002]


In [14]:
#Statistical Functions
print("\nMean:", np.mean(prices))
print("Median:", np.median(prices))
print("Std Dev:", np.std(prices))
print("50th Percentile:", np.percentile(prices, 50))



Mean: 419.0007329207136
Median: 378.670013
Std Dev: 108.2363234268936
50th Percentile: 378.670013


In [15]:
#Linear Algebra
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("\nDot Product:\n", np.dot(A,B))
print("Matrix Multiplication:\n", A @ B)


Dot Product:
 [[19 22]
 [43 50]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [16]:
#Random Numbers
print("\nRandom Numbers:", np.random.rand(3))
print("Random Integers:", np.random.randint(1,10,5))


Random Numbers: [0.2002096  0.91614341 0.83997713]
Random Integers: [9 3 2 1 6]


In [17]:
#Stock Analysis
change = np.diff(prices)

print("\nDaily Changes (first 5):", change[:5])
print("Max Price:", np.max(prices))
print("Min Price:", np.min(prices))


Daily Changes (first 5): [ 11.460006  -1.160003 -14.459992  -0.630005   8.480011]
Max Price: 691.690002
Min Price: 233.880005
